// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo0QR0M2wEHzk2o73b4v9ksdgxcdHoqjA',
    appId: '1:468972636774:web:dd3d7976b6ee1331a87ba7',
    messagingSenderId: '468972636774',
    projectId: 'thewiseworks-website',
    authDomain: 'thewiseworks-website.firebaseapp.com',
    storageBucket: 'thewiseworks-website.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd3sbdhpH-WTJHwVDw-xpbXlVjVfYB1wI',
    appId: '1:468972636774:android:5c77917edbd16adaa87ba7',
    messagingSenderId: '468972636774',
    projectId: 'thewiseworks-website',
    storageBucket: 'thewiseworks-website.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwCy3oZTscPuR87gZNcZ7phO1h4aH9rVc',
    appId: '1:468972636774:ios:d7b3d9723dcc99dda87ba7',
    messagingSenderId: '468972636774',
    projectId: 'thewiseworks-website',
    storageBucket: 'thewiseworks-website.appspot.com',
    iosClientId: '468972636774-d8toqjc0n94ijs0huup7ag8t6daa80g3.apps.googleusercontent.com',
    iosBundleId: 'com.example.wiseintern',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwCy3oZTscPuR87gZNcZ7phO1h4aH9rVc',
    appId: '1:468972636774:ios:d7b3d9723dcc99dda87ba7',
    messagingSenderId: '468972636774',
    projectId: 'thewiseworks-website',
    storageBucket: 'thewiseworks-website.appspot.com',
    iosClientId: '468972636774-d8toqjc0n94ijs0huup7ag8t6daa80g3.apps.googleusercontent.com',
    iosBundleId: 'com.example.wiseintern',
  );
}
